### ISSUE TITLE
Some TestCafe corrections

### ISSUE THREAD

**Issue by superroma** [nanoflat/articles#1]
Hi, you are mentioned TestCafe price $499 in the article https://github.com/nanoflat/articles/blob/master/cypress%20and%20other%20non-selenium%20e2e%20testing%20tools.md

Open source TestCafe is completely free and open source: https://github.com/devexpress/testcafe
And this is a version built by developers for developers. 

While Developer Express has $499 TestCafe for 5 years, this is not the product you are comparing here - please check [TestCafe FAQ](
http://devexpress.github.io/testcafe/faq/#what-is-the-difference-between-a-paid-and-an-open-source-testcafe-version-what-is-testcafe-studio)

Upcoming [TestCafe Studio](
https://testcafe-studio.devexpress.com/) is, at this point as free as Cypress (Preview/Beta), and its pricing yet to be decided.

**Comment by nanoflat** [comment]
Thanks for the feedback! You are right, I made a mistake with TestCafe, will correct it. Also partially agree with "built by developers for developers", I see a lot of QA-oriented features (like PO pattern), may be best to phrase it as "built by developers for test automation engineers".

BTW, just curious - how did you found this article? I didn't post it anywhere yet :)

**Comment by superroma** [comment]
> BTW, just curious - how did you found this article? I didn't post it anywhere yet :)

Somebody twitted about it: https://twitter.com/maaretp/status/1035824150835867649
